apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-no-resources
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-no-resources
  template:
    metadata:
      labels:
        app: nginx-no-resources
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.0
        ports:
        - containerPort: 80
        # No resource limits 