apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-limits
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.21.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "100m" 