apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-hostpath
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.21.0
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config 