apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-partial-limits
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.21.0
    resources:
      limits:
        memory: "128Mi"
        # CPU resource limit is missing 