apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-hostpath
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.21.0
    volumeMounts:
    - name: host-volume
      mountPath: /host-data
  volumes:
  - name: host-volume
    hostPath:
      path: /data
      type: Directory 