kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kadprobe-e2e
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        feature-gates: "ValidatingAdmissionPolicy=true"
        runtime-config: "admissionregistration.k8s.io/v1alpha1=true"
- role: worker 