name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run unit tests
      run: go test -v -race ./...
    
    - name: Build binary
      run: go build -o kube-vap-test ./cmd/kube-vap-test
    
    - name: Verify binary
      run: ./kube-vap-test version

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m

  e2e-test:
    name: E2E Test (Local Mode)
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build
      run: make build
    
    - name: Run E2E tests (local mode)
      run: |
        # Test run command with test files
        ./bin/kube-vap-test run examples/tests/no-latest-tag-test.yaml
        ./bin/kube-vap-test run examples/tests/resource-limits-test.yaml
        
        # Test check command with local resources
        ./bin/kube-vap-test check examples/manifests/denied-pod-latest-tag.yaml \
          --policy examples/policies/no-latest-tag-policy.yaml
        ./bin/kube-vap-test check examples/manifests/allowed-pod-specific-tag.yaml \
          --policy examples/policies/no-latest-tag-policy.yaml